# We don't use version 3.x, so that memory limits work. Versions 3.x are
# intended to be used with "swarm mode" which we don't use anyway.
version: "2.4"

services:
  ipasimulator:
    image: ipasimulator
    build: .
    volumes:
      - type: bind
        source: .
        target: c:/project
    mem_limit: 2G
